name: Pull Request on dev/main - Develop Project

on:
  workflow_dispatch:
  pull_request:
    branches: [dev, main]
    paths:
      - 'develop-project/**'

jobs:  
  test_on_dev_main:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ./develop-project


      - name: Run pytest
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          QDRANT_URL: ${{ secrets.QDRANT_URL }}
          QDRANT_COLECTION: ${{ secrets.QDRANT_COLECTION }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          MODEL_GEMINI: ${{ secrets.MODEL_GEMINI }}
          MODEL_EMBEDDING: ${{ secrets.MODEL_EMBEDDING }}
          MODEL_RERANKING: ${{ secrets.MODEL_RERANKING }}
        run: python -m pytest -q --disable-warnings --maxfail=1
        working-directory: ./develop-project
