name: CI on dev and Pull Request

on:
  workflow_dispatch:
  push:
    branches:
      - dev
    paths:
      - 'develop-project/**'

jobs:  
  test_on_dev:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ./develop-project


      - name: Run pytest
        # env:    
        #   DATABASE_URL: "mysql+pymysql://myuser:mypassword@localhost:3306/mydatabase"
        #   QDRANT_URL: "http://localhost:6333"
        #   QDRANT_COLECTION: "tamanh-hospital"
        #   MYSQL_URL: "mysql+pymysql://myuser:mypassword@localhost:3306/mydatabase"
        #   GOOGLE_API_KEY: "AIzaSyAwg37GHJeUfUhOzX6V7ddRTTdYUrpu-Qk, AIzaSyBTtbdq-kO_zq6B0IO81-QpORolRddhnQ4"
        #   MODEL_GEMINI: "gemini-2.5-flash"
        #   MODEL_EMBEDDING: "dangvantuan/vietnamese-embedding"
        #   MODEL_RERANKING: "itdainb/PhoRanker"
        run: python -m pytest -q --disable-warnings --maxfail=1
        working-directory: ./develop-project
